### ISSUE TITLE
Remove bash dependency

### ISSUE THREAD

**Issue by crosser** [kevlar1818/is_my_password_pwned#3]
This should work with any (Bourne-derived) shell, and does not depend on python:
```
#!/bin/sh
# Depends: openssl, curl, awk, tr, cut, grep
# Does not depend on 'bash'

if [ -z "$1" ]; then
        echo -n 'Enter password to check: '
        read pass
else
        pass=$1
fi

hash=`echo -n $pass|openssl sha1|awk '{print $2}'|tr '[a-z]' '[A-Z]'`
pfx=`echo $hash|cut -b-5`
sfx=`echo $hash|cut -b6-`

result=`curl -s https://api.pwnedpasswords.com/range/$pfx \
        |grep $sfx|cut -d: -f2|tr -d -c '[:digit:]'`
if [ -z "$result" ]; then
        echo 'Congratulations! It is not in the database.'
else
        echo 'Found' $result 'times!'
fi
```
`curl` writes byte-to-byte what it has got from the webservice, an webservice apparenty terminates the lines with CRLF. That's why you've got that extra "unprintable" carriage return character.

**Comment by netscylla** [comment]
Not perfect, but I just changed the count line, throws a warning but still works:
` count=${raw_count#0}`

```
sh pwned.sh  "password"
Reminder: This tool does not check password strength!
Hash prefix: 5baa6
Hash suffix: 1e4c9b93f3f0682250b6cf8331b7ee68fd8
Looking up your password...
: not completely converted003
Your password appears in the Pwned Passwords database 3303003 time(s).
Your password is thoroughly pwned! DO NOT use this password for any reason!
```

**Comment by kevin-hanselman** [comment]
I applaud the effort to remove Bash, but I don't want to part with `read -s` until I have something decent (readable and concise) to replace it. I've taken a few pointers from the OP and added `openssl sha1`. I've also replaced my uses of `echo -n` in preparation for a future Bash-ectomy.
