### ISSUE TITLE
Fails to run on Windows Subsystem for Linux (Win10)

### ISSUE THREAD

**Issue by ghost** [kevlar1818/is_my_password_pwned#5]
Fails to execute. 

![imagen](https://user-images.githubusercontent.com/33347027/36680272-921ede74-1b15-11e8-93cc-9c781205e9a3.png)

**Comment by kevin-hanselman** [comment]
Are you running on the Windows Subsystem for Linux?

**Comment by ghost** [comment]
Yes.

**Comment by cericson** [comment]
@chiwaka: Is your git configured to add carriage returns (in the normal Windows style) to line endings? Your error looks quite similar to the one here: https://github.com/rbenv/rbenv/issues/1045

**Comment by ryanhalliday-arlo** [comment]
I posted a fix in rbenv as well - simply run `dos2unix` on `pwned_pass.sh`

@kevlar1818 You should be able to close this :)
