### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by yuriw** [kevlar1818/is_my_password_pwned#8]
It’d be great if there was an option to search based of manually created `sha1` based on a password, so people feel more comfortable using this tool

**Comment by kevin-hanselman** [comment]
I appreciate the sentiment, and I intentionally wrote this script to be easy to audit. A simple code inspection will show that this script is doing nothing malicious -- in fact, it's doing only slightly more than what amounts to `password | cut | sha1sum | curl`. In a forthcoming update it'll treat entered passwords with even more care.

**Comment by yuriw** [comment]
@kevlar1818 it’s not about auditing your script, I have no doubts about it, it’s about making people `comfortable` using the website.   I sent the link to your website to ~10k people in my high tech company, and first reaction was - don’t enter your passwords to any website, and then when people looked at what it does it’s became more clear.  But that’s friendly crowd :). What about non technically suvvy people?  Hope it makes sense ...

**Comment by kevin-hanselman** [comment]
@yuriw What website are you referring to? I want to stress that I am in no way affiliated with haveibeenpwned.com or it's author, Troy Hunt. I simply made a Bash script that queries Troy Hunt's Pwned Passwords service.

If you're referring to this Github page (i.e. the README), then I would encourage your colleagues -- and all others viewing this repository, for that matter -- to read the two prominent links at the beginning of said README which explains the Pwned Passwords service and how it can be accessed securely.

**Comment by yuriw** [comment]
@kevlar1818 or really?! That’s my bad I was confused .  You are not connected whatsoever?
The reason for confusion was that this video 
https://youtu.be/N5pt4xgxC5E mentioned both and I assumed it’s the same thing.

**Comment by kevin-hanselman** [comment]
Thanks for linking to that video! It's great that people are finding this script helpful and easy to use.

To confirm: I'm in no way affiliated with the Pwned Passwords service, Troy Hunt, or the maker of that video.
